<?php

namespace App\Imports;

use App\Models\Schools;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class SchoolsImport implements ToModel, WithHeadingRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        // dd($row['website']);

        // return new Schools([
        //     'user_id' => 1,
        //     'name' => $row['name'],
        //     'website' => $row['website'],
        //     'school_email' => $row['school_email'],
        //     'school_phone' => $row['school_phone'],
        //     'country' => $row['country'],
        //     'slug' => $row['slug'],
        //     'status' => 'Approved',
        //     'featured' => 'No',
        // ]);
        
        return new Schools([

            'user_id' => 1,
            'name' => $row['name'],
            'website' => $row['website'],
            'school_email' => $row['school_email'],
            'school_phone' => $row['school_phone'],
            'country' => $row['country'],
            'slug' => $row['slug'],
            'featured_image' => $row['featured_image'],
            'images' => null,
            'facebook' => $row['facebook'],
            'instagram' => $row['instagram'],
            'twitter' => $row['twitter'],
            'you_tube' => $row['you_tube'],
            'linked_in' => $row['linked_in'],
            'vk' => $row['vk'],
            'main_button_title' => $row['main_button_title'],
            'main_button_sub_title' => $row['main_button_sub_title'],
            'main_button_link' => $row['main_button_link'],
            'other_button_title' => $row['other_button_title'],
            'other_button_link' => $row['other_button_link'],
            'quick_facts_status' => 'Yes',
            'overview_status' => 'Yes',
            'programs_status' => 'Yes',
            'admissions_status' => 'Yes',
            'financial_status' => 'Yes',
            'scholarships_status' => 'Yes',
            'contacts_status' => 'Yes',
            'location' => $row['location'],
            'school_type' => $row['school_type'],
            'language' => $row['language'],
            'undergraduates' => $row['undergraduates'],
            'entrance_dates' => $row['entrance_dates'],
            'canadian_tuition_fee' => $row['canadian_tuition_fee'],
            'international_tuition_fee' => $row['international_tuition_fee'],
            'fax' => $row['fax'],
            'address' => $row['address'],
            'link_1_name' => $row['link_1_name'],
            'link_1_url' => $row['link_1_url'],
            'link_2_name' => $row['link_2_name'],
            'link_2_url' => $row['link_2_url'],
            'link_3_name' => $row['link_3_name'],
            'link_3_url' => $row['link_3_url'],
            'link_4_name' => $row['link_4_name'],
            'link_4_url' => $row['link_4_url'],
            'link_5_name' => $row['link_5_name'],
            'link_5_url' => $row['link_5_url'],
            'link_6_name' => $row['link_6_name'],
            'link_6_url' => $row['link_6_url'],
            'link_7_name' => $row['link_7_name'],
            'link_7_url' => $row['link_7_url'],
            'link_8_name' => $row['link_8_name'],
            'link_8_url' => $row['link_8_url'],
            'start_date' => $row['start_date'],
            'online_distance_education' => $row['online_distance_education'],
            'minimum_gpa' => $row['minimum_gpa'],
            'conditional_acceptance' => $row['conditional_acceptance'],
            'graduate_program_type' => $row['graduate_program_type'],
            'under_graduate_program_type' => $row['under_graduate_program_type'],
            'study_method' => $row['study_method'],
            'delivery_mode' => $row['delivery_mode'],
            // 'tuition_range' => $row['tuition_range'],
            'accommodation' => $row['accommodation'],
            'work_on_campus' => $row['work_on_campus'],
            'work_during_holidays' => $row['work_during_holidays'],
            'internship' => $row['internship'],
            'co_op_education' => $row['co_op_education'],
            'job_placement' => $row['job_placement'],
            'financial_aid_domestic' => $row['financial_aid_domestic'],
            'financial_aid_international' => $row['financial_aid_international'],
            'research' => $row['research'],
            'exchange_programs' => $row['exchange_programs'],
            'degree_modifier' => $row['degree_modifier'],
            'day_care' => $row['day_care'],
            'elementary_school' => $row['elementary_school'],
            'immigration_office' => $row['immigration_office'],
            'career_planning' => $row['career_planning'],
            'pathway_programs' => $row['pathway_programs'],
            'employment_rates' => $row['employment_rates'],
            'class_size_undergraduate' => $row['class_size_undergraduate'],
            'class_size_masters' => $row['class_size_masters'],
            'service_and_guidance_new_students' => $row['service_and_guidance_new_students'],
            'service_and_guidance_new_arrivals' => $row['service_and_guidance_new_arrivals'],
            'contacts_page_paragraph' => $row['contacts_page_paragraph'],
            'quick_facts_title_1' => $row['quick_facts_title_1'],
            'quick_facts_title_1_paragraph' => $row['quick_facts_title_1_paragraph'],
            'quick_facts_title_2' => $row['quick_facts_title_2'],
            'quick_facts_title_2_image' => $row['quick_facts_title_2_image'],
            'quick_facts_title_2_sub_title' => $row['quick_facts_title_2_sub_title'],
            'quick_facts_title_2_paragraph' => $row['quick_facts_title_2_paragraph'],
            'quick_facts_title_2_button' => $row['quick_facts_title_2_button'],
            'quick_facts_title_2_link' => $row['quick_facts_title_2_link'],
            'quick_facts_title_2_image_name' => $row['quick_facts_title_2_image_name'],
            'programs_page_paragraph' => $row['programs_page_paragraph'],
            'programs_title_1' => $row['programs_title_1'],
            'scholarships_title_1' => $row['scholarships_title_1'],
            'scholarships_title_1_paragraph' => $row['scholarships_title_1_paragraph'],
            'scholarships_text_content_1' => $row['scholarships_text_content_1'],
            'scholarships_text_content_2' => $row['scholarships_text_content_2'],
            'scholarships_title_2' => $row['scholarships_title_2'],
            'scholarships_title_2_image' => $row['scholarships_title_2_image'],
            'scholarships_title_2_sub_title' => $row['scholarships_title_2_sub_title'],
            'scholarships_title_2_paragraph' => $row['scholarships_title_2_paragraph'],
            'scholarships_title_2_button' => $row['scholarships_title_2_button'],
            'scholarships_title_2_link' => $row['scholarships_title_2_link'],
            'scholarships_title_2_image_name' => $row['scholarships_title_2_image_name'],
            'scholarships_title_3' => $row['scholarships_title_3'],
            'scholarships_title_3_paragraph' => $row['scholarships_title_3_paragraph'],
            'scholarships_text_content_3' => $row['scholarships_text_content_3'],
            'scholarships_title_4' => $row['scholarships_title_4'],
            'scholarships_title_4_image' => $row['scholarships_title_4_image'],
            'scholarships_title_4_sub_title' => $row['scholarships_title_4_sub_title'],
            'scholarships_title_4_paragraph' => $row['scholarships_title_4_paragraph'],
            'scholarships_title_4_button' => $row['scholarships_title_4_button'],
            'scholarships_title_4_link' => $row['scholarships_title_4_link'],
            'scholarships_title_4_image_name' => $row['scholarships_title_4_image_name'],
            'overview_title_1' => $row['overview_title_1'],
            'overview_title_1_paragraph' => $row['overview_title_1_paragraph'],
            'overview_text_content_1' => $row['overview_text_content_1'],
            'overview_title_2' => $row['overview_title_2'],
            'overview_title_2_bullets' => $row['overview_title_2_bullets'],
            'overview_title_3_image' => $row['overview_title_3_image'],
            'overview_title_3_sub_title' => $row['overview_title_3_sub_title'],
            'overview_title_3_paragraph' => $row['overview_title_3_paragraph'],
            'overview_title_3_link' => $row['overview_title_3_link'],
            'overview_title_3_image_name' => $row['overview_title_3_image_name'],
            'overview_title_3_date' => $row['overview_title_3_date'],
            'overview_title_3_button' => $row['overview_title_3_button'],
            'overview_title_4' => $row['overview_title_4'],
            'overview_title_4_paragraph' => $row['overview_title_4_paragraph'],
            'overview_title_4_image' => $row['overview_title_4_image'],
            'overview_title_5' => $row['overview_title_5'],
            'overview_title_5_paragraph' => $row['overview_title_5_paragraph'],
            'overview_title_6' => $row['overview_title_6'],
            'overview_title_6_paragraph' => $row['overview_title_6_paragraph'],
            'overview_title_6_button' => $row['overview_title_6_button'],
            'overview_title_6_link' => $row['overview_title_6_link'],
            'overview_title_7' => $row['overview_title_7'],
            'overview_title_7_paragraph' => $row['overview_title_7_paragraph'],
            'overview_title_8' => $row['overview_title_8'],
            'overview_title_8_paragraph' => $row['overview_title_8_paragraph'],
            'overview_title_8_link' => $row['overview_title_8_link'],
            'overview_title_8_button' => $row['overview_title_8_button'],
            'overview_title_9' => $row['overview_title_9'],
            'overview_title_9_image' => $row['overview_title_9_image'],
            'overview_title_9_sub_title' => $row['overview_title_9_sub_title'],
            'overview_title_9_paragraph' => $row['overview_title_9_paragraph'],
            'overview_title_9_button' => $row['overview_title_9_button'],
            'overview_title_9_link' => $row['overview_title_9_link'],
            'overview_title_9_image_name' => $row['overview_title_9_image_name'],
            'overview_title_10' => $row['overview_title_10'],
            'overview_title_10_paragraph' => $row['overview_title_10_paragraph'],
            'overview_related_programs' => $row['overview_related_programs'],
            'overview_title_11' => $row['overview_title_11'],
            'overview_title_11_paragraph' => $row['overview_title_11_paragraph'],
            'overview_title_12' => $row['overview_title_12'],
            'overview_title_12_bullets' => $row['overview_title_12_bullets'],
            'overview_title_13' => $row['overview_title_13'],
            'overview_title_13_paragraph' => $row['overview_title_13_paragraph'],
            'admission_paragraph' => $row['admission_paragraph'],
            'admission_title_1' => $row['admission_title_1'],
            'admission_title_1_paragraph' => $row['admission_title_1_paragraph'],
            'admission_text_content_1' => $row['admission_text_content_1'],
            'admission_title_2' => $row['admission_title_2'],
            'admission_title_2_bullets' => $row['admission_title_2_bullets'],
            'admission_title_3' => $row['admission_title_3'],
            'admission_title_3_paragraph' => $row['admission_title_3_paragraph'],
            'admission_title_4' => $row['admission_title_4'],
            'admission_title_4_paragraph' => $row['admission_title_4_paragraph'],
            'admission_title_5' => $row['admission_title_5'],
            'admission_title_5_paragraph' => $row['admission_title_5_paragraph'],
            'financial_title_1' => $row['financial_title_1'],
            'financial_title_1_paragraph' => $row['financial_title_1_paragraph'],
            'financial_title_2' => $row['financial_title_2'],
            'financial_title_2_tab_1' => $row['financial_title_2_tab_1'],
            'financial_title_2_tab_2' => $row['financial_title_2_tab_2'],
            'financial_title_2_tab_3' => $row['financial_title_2_tab_3'],
            'financial_tab_1_sub_title_1' => $row['financial_tab_1_sub_title_1'],
            'financial_tab_1_sub_title_1_bullet' => $row['financial_tab_1_sub_title_1_bullet'],
            'financial_tab_1_sub_title_1_bullet_price' => $row['financial_tab_1_sub_title_1_bullet_price'],
            'financial_tab_1_sub_title_2' => $row['financial_tab_1_sub_title_2'],
            'financial_tab_1_sub_title_2_paragraph' => $row['financial_tab_1_sub_title_2_paragraph'],
            'financial_tab_1_sub_title_3' => $row['financial_tab_1_sub_title_3'],
            'financial_tab_1_sub_title_3_bullet_1' => $row['financial_tab_1_sub_title_3_bullet_1'],
            'financial_tab_1_sub_title_3_bullet_1_price' => $row['financial_tab_1_sub_title_3_bullet_1_price'],
            'financial_tab_1_sub_title_3_bullet_2' => $row['financial_tab_1_sub_title_3_bullet_2'],
            'financial_tab_1_sub_title_3_bullet_2_price' => $row['financial_tab_1_sub_title_3_bullet_2_price'],
            'financial_tab_1_sub_title_3_bullet_3' => $row['financial_tab_1_sub_title_3_bullet_3'],
            'financial_tab_1_sub_title_3_bullet_3_price' => $row['financial_tab_1_sub_title_3_bullet_3_price'],
            'financial_tab_1_sub_title_3_paragraph' => $row['financial_tab_1_sub_title_3_paragraph'],
            'financial_tab_2_sub_title_1' => $row['financial_tab_2_sub_title_1'],
            'financial_tab_2_sub_title_1_bullet' => $row['financial_tab_2_sub_title_1_bullet'],
            'financial_tab_2_sub_title_1_bullet_price' => $row['financial_tab_2_sub_title_1_bullet_price'],
            'financial_tab_2_sub_title_2' => $row['financial_tab_2_sub_title_2'],
            'financial_tab_2_sub_title_2_paragraph' => $row['financial_tab_2_sub_title_2_paragraph'],
            'financial_tab_2_sub_title_3' => $row['financial_tab_2_sub_title_3'],
            'financial_tab_2_sub_title_3_bullet_1' => $row['financial_tab_2_sub_title_3_bullet_1'],
            'financial_tab_2_sub_title_3_bullet_1_price' => $row['financial_tab_2_sub_title_3_bullet_1_price'],
            'financial_tab_2_sub_title_3_bullet_2' => $row['financial_tab_2_sub_title_3_bullet_2'],
            'financial_tab_2_sub_title_3_bullet_2_price' => $row['financial_tab_2_sub_title_3_bullet_2_price'],
            'financial_tab_2_sub_title_3_bullet_3' => $row['financial_tab_2_sub_title_3_bullet_3'],
            'financial_tab_2_sub_title_3_bullet_3_price' => $row['financial_tab_2_sub_title_3_bullet_3_price'],
            'financial_tab_2_sub_title_3_paragraph' => $row['financial_tab_2_sub_title_3_paragraph'],
            'financial_tab_3_sub_title_1' => $row['financial_tab_3_sub_title_1'],
            'financial_tab_3_sub_title_1_bullet' => $row['financial_tab_3_sub_title_1_bullet'],
            'financial_tab_3_sub_title_1_bullet_price' => $row['financial_tab_3_sub_title_1_bullet_price'],
            'financial_tab_3_sub_title_2' => $row['financial_tab_3_sub_title_2'],
            'financial_tab_3_sub_title_2_paragraph' => $row['financial_tab_3_sub_title_2_paragraph'],
            'financial_tab_3_sub_title_3' => $row['financial_tab_3_sub_title_3'],
            'financial_tab_3_sub_title_3_bullet_1' => $row['financial_tab_3_sub_title_3_bullet_1'],
            'financial_tab_3_sub_title_3_bullet_1_price' => $row['financial_tab_3_sub_title_3_bullet_1_price'],
            'financial_tab_3_sub_title_3_bullet_2' => $row['financial_tab_3_sub_title_3_bullet_2'],
            'financial_tab_3_sub_title_3_bullet_2_price' => $row['financial_tab_3_sub_title_3_bullet_2_price'],
            'financial_tab_3_sub_title_3_bullet_3' => $row['financial_tab_3_sub_title_3_bullet_3'],
            'financial_tab_3_sub_title_3_bullet_3_price' => $row['financial_tab_3_sub_title_3_bullet_3_price'],
            'financial_tab_3_sub_title_3_paragraph' => $row['financial_tab_3_sub_title_3_paragraph'],
            'financial_title_3' => $row['financial_title_3'],
            'financial_title_3_paragraph' => $row['financial_title_3_paragraph'],
            'financial_title_4' => $row['financial_title_4'],
            'financial_title_4_paragraph' => $row['financial_title_4_paragraph'],
            'financial_related_programs_4' => $row['financial_related_programs_4'],
            'financial_title_5' => $row['financial_title_5'],
            'financial_title_5_paragraph' => $row['financial_title_5_paragraph'],
            'financial_title_6' => $row['financial_title_6'],
            'financial_title_6_paragraph' => $row['financial_title_6_paragraph'],
            'financial_text_content_1' => $row['financial_text_content_1'],
            'marked_facts' => $row['marked_facts'],
            'status' => 'Approved',
            'featured' => 'No',

        ]);
    }
}
